### ISSUE TITLE
Fail to run npm run dev

### ISSUE THREAD

**Issue by oswaldoacauan** [jhen0409/react-chrome-extension-boilerplate#33]
When i tried to run `npm run dev` this is the output.

**terminal output**
```
> react-chrome-extension-boilerplate@0.8.1 dev /var/www/chrome-extension
> node scripts/dev

/var/www/chrome-extension/scripts/tasks.js:3
exports.replaceWebpack = () => {
                          ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/chrome-extension/scripts/dev.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Linux 3.19.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! react-chrome-extension-boilerplate@0.8.1 dev: `node scripts/dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-chrome-extension-boilerplate@0.8.1 dev script 'node scripts/dev'.
npm ERR! This is most likely a problem with the react-chrome-extension-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-chrome-extension-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/chrome-extension/npm-debug.log
```

**npm-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev react-chrome-extension-boilerplate@0.8.1
6 info dev react-chrome-extension-boilerplate@0.8.1
7 verbose unsafe-perm in lifecycle true
8 info react-chrome-extension-boilerplate@0.8.1 Failed to exec dev script
9 verbose stack Error: react-chrome-extension-boilerplate@0.8.1 dev: `node scripts/dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid react-chrome-extension-boilerplate@0.8.1
11 verbose cwd /var/www/chrome-extension
12 error Linux 3.19.0-43-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error react-chrome-extension-boilerplate@0.8.1 dev: `node scripts/dev`
17 error Exit status 1
18 error Failed at the react-chrome-extension-boilerplate@0.8.1 dev script 'node scripts/dev'.
18 error This is most likely a problem with the react-chrome-extension-boilerplate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node scripts/dev
18 error You can get their info via:
18 error     npm owner ls react-chrome-extension-boilerplate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by jhen0409** [comment]
Currently we used node@^4 compatible syntax on `scripts`, `webpack` js files, please update node version.

**Comment by oswaldoacauan** [comment]
My bad, nvm deceived me :p
