### ISSUE TITLE
`yarn run dev`, Module build failed: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by HaveF** [jhen0409/react-chrome-extension-boilerplate#72]
Hi, Jhen-Jie Hong :-)

`yarn run dev`

```
yarn run v0.24.6
$ node scripts/dev
[Copy assets]
--------------------------------------------------------------------------------

  rendered /Users/HaveF/Desktop/proj/xq-helper/dev/background.html
  rendered /Users/HaveF/Desktop/proj/xq-helper/dev/inject.html
  rendered /Users/HaveF/Desktop/proj/xq-helper/dev/popup.html
  rendered /Users/HaveF/Desktop/proj/xq-helper/dev/window.html
[Webpack Dev]
--------------------------------------------------------------------------------
If you're developing Inject page,
please allow `https://localhost:3000` connections in Google Chrome,
and load unpacked extensions with `./dev` folder. (see https://developer.chrome.com/extensions/getstarted#unpacked)

[webpack-httpolyglot-server] http(s)://localhost:3000
webpack built 03869fb5b1e89a8e5998 in 647ms
Hash: 03869fb5b1e89a8e5998
Version: webpack 1.15.0
Time: 647ms
           Asset     Size  Chunks       Chunk Names
inject.bundle.js  3.48 kB       0       main
chunk    {0} inject.bundle.js (main) 629 bytes [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] ./webpack/customPublicPath.js 589 bytes {0} [built]

ERROR in ./chrome/extension/inject.js
Module build failed: SyntaxError: Unexpected token (11:16)

   9 |   }
  10 |
> 11 |   buttonOnClick = () => {
     |                 ^
  12 |     this.setState({ isVisible: !this.state.isVisible });
  13 |   };
  14 |

 @ multi main
webpack built b15585277b2fb9a9d53f in 1123ms
Hash: b15585277b2fb9a9d53f
Version: webpack 1.15.0
Time: 1123ms
               Asset    Size  Chunks       Chunk Names
background.bundle.js  754 kB       0       background
   todoapp.bundle.js  232 kB       1       todoapp
chunk    {0} background.bundle.js (background) 271 kB [rendered]
    [0] multi background 52 bytes {0} [built]
    [1] ./webpack/customPublicPath.js 589 bytes {0} {1} [built]
    [2] (webpack)-hot-middleware/client.js?path=__webpack_hmr&dynamicPublicPath=true 6.68 kB {0} {1} [built]
    [3] (webpack)/buildin/module.js 251 bytes {0} {1} [built]
    [4] ./~/querystring/index.js 127 bytes {0} {1} [built]
    [5] ./~/querystring/decode.js 2.4 kB {0} {1} [built]
    [6] ./~/querystring/encode.js 2.09 kB {0} {1} [built]
    [7] ./~/strip-ansi/index.js 161 bytes {0} {1} [built]
    [8] ./~/ansi-regex/index.js 135 bytes {0} {1} [built]
    [9] (webpack)-hot-middleware/client-overlay.js 1.82 kB {0} {1} [built]
   [10] ./~/ansi-html/index.js 4.26 kB {0} {1} [built]
   [11] ./~/html-entities/index.js 231 bytes {0} {1} [built]
   [12] ./~/html-entities/lib/xml-entities.js 2.99 kB {0} {1} [built]
   [13] ./~/html-entities/lib/html4-entities.js 6.59 kB {0} {1} [built]
   [14] ./~/html-entities/lib/html5-entities.js 49 kB {0} {1} [built]
   [15] (webpack)-hot-middleware/process-update.js 4.11 kB {0} {1} [built]
   [16] ./chrome/extension/background.js 676 bytes {0} [built] [1 error]
   [17] ./~/bluebird/js/release/bluebird.js 291 bytes {0} [built]
   [18] ./~/bluebird/js/release/promise.js 25.8 kB {0} [built]
   [19] ./~/process/browser.js 5.42 kB {0} [built]
   [20] ./~/bluebird/js/release/util.js 10.3 kB {0} [built]
   [21] ./~/bluebird/js/release/es5.js 1.98 kB {0} [built]
   [22] ./~/bluebird/js/release/async.js 4.13 kB {0} [built]
   [23] ./~/bluebird/js/release/schedule.js 2.09 kB {0} [built]
   [24] ./~/timers-browserify/main.js 1.36 kB {0} [built]
   [25] ./~/setimmediate/setImmediate.js 6.47 kB {0} [built]
   [26] ./~/bluebird/js/release/queue.js 1.87 kB {0} [built]
   [27] ./~/bluebird/js/release/errors.js 3.72 kB {0} [built]
   [28] ./~/bluebird/js/release/thenables.js 2.13 kB {0} [built]
   [29] ./~/bluebird/js/release/promise_array.js 5.21 kB {0} [built]
   [30] ./~/bluebird/js/release/context.js 2.38 kB {0} [built]
   [31] ./~/bluebird/js/release/debuggability.js 29.5 kB {0} [built]
   [32] ./~/bluebird/js/release/finally.js 4.61 kB {0} [built]
   [33] ./~/bluebird/js/release/catch_filter.js 1.43 kB {0} [built]
   [34] ./~/bluebird/js/release/nodeback.js 1.56 kB {0} [built]
   [35] ./~/bluebird/js/release/method.js 1.77 kB {0} [built]
   [36] ./~/bluebird/js/release/bind.js 1.97 kB {0} [built]
   [37] ./~/bluebird/js/release/cancel.js 3.71 kB {0} [built]
   [38] ./~/bluebird/js/release/direct_resolve.js 1.4 kB {0} [built]
   [39] ./~/bluebird/js/release/synchronous_inspection.js 2.81 kB {0} [built]
   [40] ./~/bluebird/js/release/join.js 8.22 kB {0} [built]
   [41] ./~/bluebird/js/release/map.js 5.38 kB {0} [built]
   [42] ./~/bluebird/js/release/call_get.js 4.36 kB {0} [built]
   [43] ./~/bluebird/js/release/using.js 7.53 kB {0} [built]
   [44] ./~/bluebird/js/release/timers.js 2.4 kB {0} [built]
   [45] ./~/bluebird/js/release/generators.js 7.76 kB {0} [built]
   [46] ./~/bluebird/js/release/nodeify.js 1.65 kB {0} [built]
   [47] ./~/bluebird/js/release/promisify.js 12.2 kB {0} [built]
   [48] ./~/bluebird/js/release/props.js 3.12 kB {0} [built]
   [49] ./~/bluebird/js/release/race.js 1.25 kB {0} [built]
   [50] ./~/bluebird/js/release/reduce.js 5.13 kB {0} [built]
   [51] ./~/bluebird/js/release/settle.js 1.26 kB {0} [built]
   [52] ./~/bluebird/js/release/some.js 3.96 kB {0} [built]
   [53] ./~/bluebird/js/release/filter.js 314 bytes {0} [built]
   [54] ./~/bluebird/js/release/each.js 789 bytes {0} [built]
   [55] ./~/bluebird/js/release/any.js 421 bytes {0} [built]
   [56] ./chrome/extension/background/contextMenus.js 795 bytes {0} [built]
   [58] ./chrome/extension/background/badge.js 352 bytes {0} [built]
chunk    {1} todoapp.bundle.js (todoapp) 81.5 kB [rendered]
    [0] multi todoapp 52 bytes {1} [built] [1 error]
    [1] ./webpack/customPublicPath.js 589 bytes {0} {1} [built]
    [2] (webpack)-hot-middleware/client.js?path=__webpack_hmr&dynamicPublicPath=true 6.68 kB {0} {1} [built]
    [3] (webpack)/buildin/module.js 251 bytes {0} {1} [built]
    [4] ./~/querystring/index.js 127 bytes {0} {1} [built]
    [5] ./~/querystring/decode.js 2.4 kB {0} {1} [built]
    [6] ./~/querystring/encode.js 2.09 kB {0} {1} [built]
    [7] ./~/strip-ansi/index.js 161 bytes {0} {1} [built]
    [8] ./~/ansi-regex/index.js 135 bytes {0} {1} [built]
    [9] (webpack)-hot-middleware/client-overlay.js 1.82 kB {0} {1} [built]
   [10] ./~/ansi-html/index.js 4.26 kB {0} {1} [built]
   [11] ./~/html-entities/index.js 231 bytes {0} {1} [built]
   [12] ./~/html-entities/lib/xml-entities.js 2.99 kB {0} {1} [built]
   [13] ./~/html-entities/lib/html4-entities.js 6.59 kB {0} {1} [built]
   [14] ./~/html-entities/lib/html5-entities.js 49 kB {0} {1} [built]
   [15] (webpack)-hot-middleware/process-update.js 4.11 kB {0} {1} [built]

ERROR in ./chrome/extension/todoapp.js
Module build failed: SyntaxError: Unexpected token (13:4)

  11 |
  12 |   ReactDOM.render(
> 13 |     <Root store={createStore(initialState)} />,
     |     ^
  14 |     document.querySelector('#root')
  15 |   );
  16 | });

 @ multi todoapp

ERROR in ./chrome/extension/background/inject.js
Module parse failed: /Users/HaveF/Desktop/proj/xq-helper/node_modules/babel-loader/lib/index.js?{"presets":["react-hmre"]}!/Users/HaveF/Desktop/proj/xq-helper/chrome/extension/background/inject.js Unexpected token (33:65)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (33:65)
    at Parser.pp$4.raise (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$3.parseExprList (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:2152:16)
    at Parser.pp$3.parseSubscripts (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1597:21)
 @ ./chrome/extension/background.js 25:0-30
webpack building...
webpack built b15585277b2fb9a9d53f in 68ms
Hash: b15585277b2fb9a9d53f
Version: webpack 1.15.0
Time: 68ms
               Asset    Size  Chunks       Chunk Names
background.bundle.js  754 kB       0       background
   todoapp.bundle.js  232 kB       1       todoapp
chunk    {0} background.bundle.js (background) 271 kB
    [0] multi background 52 bytes {0}
    [1] ./webpack/customPublicPath.js 589 bytes {0} {1}
    [2] (webpack)-hot-middleware/client.js?path=__webpack_hmr&dynamicPublicPath=true 6.68 kB {0} {1}
    [3] (webpack)/buildin/module.js 251 bytes {0} {1}
    [4] ./~/querystring/index.js 127 bytes {0} {1}
    [5] ./~/querystring/decode.js 2.4 kB {0} {1}
    [6] ./~/querystring/encode.js 2.09 kB {0} {1}
    [7] ./~/strip-ansi/index.js 161 bytes {0} {1}
    [8] ./~/ansi-regex/index.js 135 bytes {0} {1}
    [9] (webpack)-hot-middleware/client-overlay.js 1.82 kB {0} {1}
   [10] ./~/ansi-html/index.js 4.26 kB {0} {1}
   [11] ./~/html-entities/index.js 231 bytes {0} {1}
   [12] ./~/html-entities/lib/xml-entities.js 2.99 kB {0} {1}
   [13] ./~/html-entities/lib/html4-entities.js 6.59 kB {0} {1}
   [14] ./~/html-entities/lib/html5-entities.js 49 kB {0} {1}
   [15] (webpack)-hot-middleware/process-update.js 4.11 kB {0} {1}
   [16] ./chrome/extension/background.js 676 bytes {0} [2 errors]
   [17] ./~/bluebird/js/release/bluebird.js 291 bytes {0}
   [18] ./~/bluebird/js/release/promise.js 25.8 kB {0}
   [19] ./~/process/browser.js 5.42 kB {0}
   [20] ./~/bluebird/js/release/util.js 10.3 kB {0}
   [21] ./~/bluebird/js/release/es5.js 1.98 kB {0}
   [22] ./~/bluebird/js/release/async.js 4.13 kB {0}
   [23] ./~/bluebird/js/release/schedule.js 2.09 kB {0}
   [24] ./~/timers-browserify/main.js 1.36 kB {0}
   [25] ./~/setimmediate/setImmediate.js 6.47 kB {0}
   [26] ./~/bluebird/js/release/queue.js 1.87 kB {0}
   [27] ./~/bluebird/js/release/errors.js 3.72 kB {0}
   [28] ./~/bluebird/js/release/thenables.js 2.13 kB {0}
   [29] ./~/bluebird/js/release/promise_array.js 5.21 kB {0}
   [30] ./~/bluebird/js/release/context.js 2.38 kB {0}
   [31] ./~/bluebird/js/release/debuggability.js 29.5 kB {0}
   [32] ./~/bluebird/js/release/finally.js 4.61 kB {0}
   [33] ./~/bluebird/js/release/catch_filter.js 1.43 kB {0}
   [34] ./~/bluebird/js/release/nodeback.js 1.56 kB {0}
   [35] ./~/bluebird/js/release/method.js 1.77 kB {0}
   [36] ./~/bluebird/js/release/bind.js 1.97 kB {0}
   [37] ./~/bluebird/js/release/cancel.js 3.71 kB {0}
   [38] ./~/bluebird/js/release/direct_resolve.js 1.4 kB {0}
   [39] ./~/bluebird/js/release/synchronous_inspection.js 2.81 kB {0}
   [40] ./~/bluebird/js/release/join.js 8.22 kB {0}
   [41] ./~/bluebird/js/release/map.js 5.38 kB {0}
   [42] ./~/bluebird/js/release/call_get.js 4.36 kB {0}
   [43] ./~/bluebird/js/release/using.js 7.53 kB {0}
   [44] ./~/bluebird/js/release/timers.js 2.4 kB {0}
   [45] ./~/bluebird/js/release/generators.js 7.76 kB {0}
   [46] ./~/bluebird/js/release/nodeify.js 1.65 kB {0}
   [47] ./~/bluebird/js/release/promisify.js 12.2 kB {0}
   [48] ./~/bluebird/js/release/props.js 3.12 kB {0}
   [49] ./~/bluebird/js/release/race.js 1.25 kB {0}
   [50] ./~/bluebird/js/release/reduce.js 5.13 kB {0}
   [51] ./~/bluebird/js/release/settle.js 1.26 kB {0}
   [52] ./~/bluebird/js/release/some.js 3.96 kB {0}
   [53] ./~/bluebird/js/release/filter.js 314 bytes {0}
   [54] ./~/bluebird/js/release/each.js 789 bytes {0}
   [55] ./~/bluebird/js/release/any.js 421 bytes {0}
   [56] ./chrome/extension/background/contextMenus.js 795 bytes {0}
   [58] ./chrome/extension/background/badge.js 352 bytes {0}
chunk    {1} todoapp.bundle.js (todoapp) 81.5 kB
    [0] multi todoapp 52 bytes {1} [2 errors]
    [1] ./webpack/customPublicPath.js 589 bytes {0} {1}
    [2] (webpack)-hot-middleware/client.js?path=__webpack_hmr&dynamicPublicPath=true 6.68 kB {0} {1}
    [3] (webpack)/buildin/module.js 251 bytes {0} {1}
    [4] ./~/querystring/index.js 127 bytes {0} {1}
    [5] ./~/querystring/decode.js 2.4 kB {0} {1}
    [6] ./~/querystring/encode.js 2.09 kB {0} {1}
    [7] ./~/strip-ansi/index.js 161 bytes {0} {1}
    [8] ./~/ansi-regex/index.js 135 bytes {0} {1}
    [9] (webpack)-hot-middleware/client-overlay.js 1.82 kB {0} {1}
   [10] ./~/ansi-html/index.js 4.26 kB {0} {1}
   [11] ./~/html-entities/index.js 231 bytes {0} {1}
   [12] ./~/html-entities/lib/xml-entities.js 2.99 kB {0} {1}
   [13] ./~/html-entities/lib/html4-entities.js 6.59 kB {0} {1}
   [14] ./~/html-entities/lib/html5-entities.js 49 kB {0} {1}
   [15] (webpack)-hot-middleware/process-update.js 4.11 kB {0} {1}

ERROR in ./chrome/extension/todoapp.js
Module build failed: SyntaxError: Unexpected token (13:4)

  11 |
  12 |   ReactDOM.render(
> 13 |     <Root store={createStore(initialState)} />,
     |     ^
  14 |     document.querySelector('#root')
  15 |   );
  16 | });

 @ multi todoapp

ERROR in ./chrome/extension/background/inject.js
Module parse failed: /Users/HaveF/Desktop/proj/xq-helper/node_modules/babel-loader/lib/index.js?{"presets":["react-hmre"]}!/Users/HaveF/Desktop/proj/xq-helper/chrome/extension/background/inject.js Unexpected token (33:65)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (33:65)
    at Parser.pp$4.raise (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$3.parseExprList (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:2152:16)
    at Parser.pp$3.parseSubscripts (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/HaveF/Desktop/proj/xq-helper/node_modules/acorn/dist/acorn.js:1597:21)
 @ ./chrome/extension/background.js 25:0-30
```

node --version
v8.1.3
npm --version
5.0.3

Have any idea? thanks!

**Comment by HaveF** [comment]
totally fine with clean clone and `npm install`, strange!
